service: sanity-meetup-game-lambda

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs12.x

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

plugins:
  - serverless-plugin-chrome
  - serverless-offline

functions:
  screenshot:
    description: Headless Chrome Serverless-framework screenshot example
    memorySize: 1536
    timeout: 30
    handler: handler.screenshot
    events:
      - http:
          path: screenshot
          method: get
